### ISSUE TITLE
Provide public API?

### ISSUE THREAD

**Issue by nguoianphu** [DeathbyToast/PvP_IVs#43]
Hi, thanks for great tools.
I'm using your site to generate GL & UL best IVs and put them into my [site](https://github.com/nguoianphu/pkmn.help). Can you make output results to JSON, like [this](https://github.com/nguoianphu/pkmn.help/blob/vitejs/src/data-pvp-gl.json)? Why?
- Your site doesn't have API to get results (or I don't see them)
- We have to query [the Game Master JSON](https://raw.githubusercontent.com/PokeMiners/game_masters/master/latest/latest.json) each time we want to get any result. It's slow & we have to depend on the Game Master. If the Game master is having issue, then we too.

**Comment by DeathbyToast** [comment]
Correct, there is no API for this site as it is completely static webpages; there is no "server" to respond to API requests here as the site is hosted and run for free on GitHub pages: https://pages.github.com/

That being said, you're welcome to run the ranking algorithm yourself (which is what the site does for every page load). I've done my best to keep it lightweight so that it runs quickly. It is found here: https://github.com/DeathbyToast/PvP_IVs/blob/master/includes/calculate.js

Hopefully my comments are clear enough, but if anything is confusing just let me know and I'm happy to expand the documentation. Also worth checking out the Readme for more on how the site works overall: https://github.com/DeathbyToast/PvP_IVs#readme

**Comment by DeathbyToast** [comment]
Correct, there is no API for this site as it is completely static webpages; there is no "server" to respond to API requests here as the site is hosted and run for free on GitHub pages: https://pages.github.com/

That being said, you're welcome to run the ranking algorithm yourself (which is what the site does for every page load). I've done my best to keep it lightweight so that it runs quickly. It is found here: https://github.com/DeathbyToast/PvP_IVs/blob/master/includes/calculate.js

Hopefully my comments are clear enough, but if anything is confusing just let me know and I'm happy to expand the documentation. Also worth checking out the Readme for more on how the site works overall: https://github.com/DeathbyToast/PvP_IVs#readme
